import Head from 'next/head';

import { useRouter } from 'next/router';

import Header from 'components/header';
import Footer from 'components/footer';

import DealerService from 'libs/DealerService/DealerService';

export default function Home({ host, id, time, cmsProperties}) {
  const router = useRouter();

  // Host available on query from router if blocking or fallback
  const query = router.query;

  // Or params
  console.log(host, id, time, query);

  return (
    <div>
      <Head>
        <title>Next Multi Host Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header host={host} />
      <h2>Home - Host: {host}</h2>
      <h1>{cmsProperties.dealerConfig.dealerName}</h1>
      <p>
        Organization ID: {cmsProperties.dealerConfig.orgId}<br/>
        <b>Generated At:</b>
        <i>{time}</i>
      </p>
      <Footer />
    </div>
  );
}

export async function getStaticProps(context) {
  // Available on server render
  console.log('getStaticProps', context);

  const host = context.params.host;

  const dealerConfig = DealerService.getByDomain(host);

  // Here we do some async logic to get properties from Headless CMS
  const cmsProperties = { dealerConfig } // for this examples sake
  // ...
  // ...

  const time = Date.now();

  return {
    props: {
      host,
      time,
      cmsProperties
    },
    // revalidate: 10,
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      { params: { host: 'domain1.com' } },
      { params: { host: 'domain2.com' } },
    ],
    fallback: 'blocking',
  };
}
